# Importando Bibliotecas

In [26]:
import pandas as pd
import numpy as np
import requests
from io import StringIO

# Importando a base de dados do GitHub

In [27]:
def carregar_csv_github(url_raw: str) -> pd.DataFrame:
    """
    Baixa um CSV público do GitHub e retorna como DataFrame pandas.
    url_raw: Caminho no GitHub para o arquivo .CSV
    """
    response = requests.get(url_raw, timeout=30)
    response.raise_for_status()

    # 1. Lê o arquivo pulando os metadados do topo
    df_lido = pd.read_csv(
        StringIO(response.text),
        sep=';',
        skiprows=1,
        on_bad_lines='skip'
    )

    # 2. Transforma a string textual 'null' no valor NaN real do sistema
    df_limpo = df_lido.replace('null', np.nan)

    # 3. Retorna o DataFrame perfeitamente estruturado
    return df_limpo

# Execução do código
csv_path = "https://raw.githubusercontent.com/Jobanu/Projeto-Final-DS-PY-004/main/Dados/V_OCORRENCIA_AMPLA.csv"
df = carregar_csv_github(csv_path)

print(f"Carregadas {len(df)} ocorrências")
df.head()

Carregadas 5021 ocorrências

,Numero_da_Ocorrencia,Numero_da_Ficha,Operador_Padronizado,Classificacao_da_Ocorrencia,Data_da_Ocorrencia,Hora_da_Ocorrencia,Municipio,UF,Regiao,Descricao_do_Tipo,...,Lesoes_Desconhecidas_Tripulantes,Lesoes_Desconhecidas_Passageiros,Lesoes_Desconhecidas_Terceiros,Modelo,CLS,Tipo_ICAO,PMD,Numero_de_Assentos,Nome_do_Fabricante,PSSO
0,36746,2023765949,NITZ AVIACAO AGRICOLA LTDA. - EPP,Acidente,2023-03-23,11:20:00,PASSO DO SOBRADO,RS,Sul,EXCURSÃO DE PISTA,...,NaN,NaN,NaN,A188B,L1P,C188,1497.0,1.0,CESSNA AIRCRAFT,verdadeiro
1,38381,202385892466,ENOCK RESENDE JUNIOR,Acidente,2023-07-09,16:00:00,SANTANA DO RIACHO,MG,Sudeste,OUTROS,...,NaN,NaN,NaN,H2,G1P,ZZZZ,500.0,2.0,ENOCK RESENDE JUNIOR,verdadeiro
2,36409,2023525502,MS ARMAZENS GERAIS LTDA.,Incidente Grave,2023-02-16,19:00:00,TAILÂNDIA,PA,Norte,COLISÃO COM OBSTÁCULO DURANTE A DECOLAGEM E POUSO,...,NaN,NaN,NaN,SR22,L1P,SR22,1542.0,4.0,CIRRUS DESIGN,verdadeiro
3,31607,2022464840,ADRIANO AUGUSTO PECLAT DE PAULA,Incidente Grave,2022-03-27,13:50,PIRENÓPOLIS,GO,Centro-Oeste,EXCURSÃO DE PISTA,...,NaN,NaN,NaN,PA-28R-201T,L1P,P28R,1315.0,4.0,PIPER AIRCRAFT,verdadeiro
4,31607,2022464840,ANTONIO PAULO MACHADO GONTIJO,Incidente Grave,2022-03-27,13:50,PIRENÓPOLIS,GO,Centro-Oeste,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,...,NaN,NaN,NaN,PA-28R-201T,L1P,P28R,1315.0,4.0,PIPER AIRCRAFT,verdadeiro

##Analisando os tipos de dados

Análise dos tipos de dados referentes a planilha da ANAC. O "int64" é um número inteiro, o "object" é uma *string* (uma entrada de texto) e o "float64" é um número positivo podendo ser racional.

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5021 entries, 0 to 5020
Data columns (total 45 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Numero_da_Ocorrencia              5021 non-null   int64
 1   Numero_da_Ficha                   5019 non-null   object
 2   Operador_Padronizado              4945 non-null   object
 3   Classificacao_da_Ocorrencia       5021 non-null   object
 4   Data_da_Ocorrencia                5021 non-null   object
 5   Hora_da_Ocorrencia                3588 non-null   object
 6   Municipio                         3627 non-null   object
 7   UF                                5018 non-null   object
 8   Regiao                            4351 non-null   object
 9   Descricao_do_Tipo                 4379 non-null   object
 10  ICAO                              1687 non-null   object
 11  Latitude                          3531 non-null   object
 12  Longitude                         3531 non-null   object
 13  Tipo_de_Aerodromo                 1572 non-null   object
 14  Historico                         4756 non-null   object
 15  Matricula                         5017 non-null   object
 16  Categoria_da_Aeronave             5012 non-null   object
 17  Operador                          4945 non-null   object
 18  Tipo_de_Ocorrencia                4379 non-null   object
 19  Fase_da_Operacao                  3721 non-null   object
 20  Operacao                          4927 non-null   object
 21  Danos_a_Aeronave                  3595 non-null   object
 22  Aerodromo_de_Destino              2883 non-null   object
 23  Aerodromo_de_Origem               2904 non-null   object
 24  Lesoes_Fatais_Tripulantes         3903 non-null   float64
 25  Lesoes_Fatais_Passageiros         3782 non-null   float64
 26  Lesoes_Fatais_Terceiros           3702 non-null   float64
 27  Lesoes_Graves_Tripulantes         3853 non-null   float64
 28  Lesoes_Graves_Passageiros         3740 non-null   float64
 29  Lesoes_Graves_Terceiros           3694 non-null   float64
 30  Lesoes_Leves_Tripulantes          3897 non-null   float64
 31  Lesoes_Leves_Passageiros          3744 non-null   float64
 32  Lesoes_Leves_Terceiros            3694 non-null   float64
 33  Ilesos_Tripulantes                4611 non-null   float64
 34  Ilesos_Passageiros                4072 non-null   float64
 35  Lesoes_Desconhecidas_Tripulantes  3706 non-null   float64
 36  Lesoes_Desconhecidas_Passageiros  3695 non-null   float64
 37  Lesoes_Desconhecidas_Terceiros    3694 non-null   float64
 38  Modelo                            4858 non-null   object
 39  CLS                               4846 non-null   object
 40  Tipo_ICAO                         4863 non-null   object
 41  PMD                               4876 non-null   float64
 42  Numero_de_Assentos                4872 non-null   float64
 43  Nome_do_Fabricante                4730 non-null   object
 44  PSSO                              5021 non-null   object
dtypes: float64(16), int64(1), object(28)
memory usage: 1.7+ MB

##Análise do total (count), média (mean), desvio padrão (std), mínimo e máximo

In [29]:
df.describe()

,Numero_da_Ocorrencia,Lesoes_Fatais_Tripulantes,Lesoes_Fatais_Passageiros,Lesoes_Fatais_Terceiros,Lesoes_Graves_Tripulantes,Lesoes_Graves_Passageiros,Lesoes_Graves_Terceiros,Lesoes_Leves_Tripulantes,Lesoes_Leves_Passageiros,Lesoes_Leves_Terceiros,Ilesos_Tripulantes,Ilesos_Passageiros,Lesoes_Desconhecidas_Tripulantes,Lesoes_Desconhecidas_Passageiros,Lesoes_Desconhecidas_Terceiros,PMD,Numero_de_Assentos
count,5021.000000,3903.000000,3782.000000,3702.000000,3853.000000,3740.000000,3694.000000,3897.000000,3744.000000,3694.000000,4611.000000,4072.000000,3706.000000,3695.000000,3694.000000,4876.000000,4872.000000
mean,12814.381000,0.222649,0.313326,0.018639,0.089022,0.068717,0.006226,0.168335,0.152511,0.008121,0.907612,3.232564,0.015111,0.017050,0.003249,3528.873052,7.507594
std,13129.158692,0.504088,3.947276,0.267946,0.308442,0.397013,0.091408,0.435693,0.735700,0.118384,1.053106,17.857695,0.138581,0.230302,0.093029,13279.101698,23.691526
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4529.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1043.000000,2.000000
50%,6532.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1633.000000,4.000000
75%,25190.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,2155.000000,6.000000
max,46147.000000,6.000000,181.000000,12.000000,2.000000,6.000000,2.000000,5.000000,18.000000,4.000000,16.000000,341.000000,2.000000,7.000000,4.000000,346544.000000,399.000000

# Tratamento das colunas dos tipos de Lesões - (NaN para 0)

A razão para escolhermos apenas as colunas de lesões e não o DataFrame inteiro é que o significado do "vazio" (NaN) muda completamente dependendo do tipo de dado da coluna. Substituir tudo por zero de forma automática geraria graves erros de lógica e distorções na análise.

1. Colunas de Texto (Strings) ficariam sem sentido.

    - Operador: O responsável pelo voo passaria a se chamar 0 (o Pandas não saberia que ali deveria ser "Desconhecido")
    Matricula: O prefixo do avião viraria 0.

2. Colunas Numéricas Específicas seriam corrompidas, pois o número 0 possui um valor matemático real em engenharia aeronáutica.

    - PMD (Peso Máximo de Decolagem): Se uma aeronave experimental não teve o peso registrado, colocar 0 faria o Pandas calcular que o avião pesa zero quilos, o que estragaria qualquer média de peso que você tentasse fazer no projeto.
    - Numero_de_Assentos: Colocar 0 indicaria que o avião voava sem nenhum banco dentro, quando na verdade o dado apenas não foi coletado.

3. Nas colunas de Lesões, o 0 mantém a lógica perfeita. Nas colunas de contagem de pessoas (Lesoes_Fatais, Lesoes_Graves), assumir que o vazio equivale a 0 é seguro e correto para o modelo de dados, pois:

    - Se o relatório não mencionou feridos, a hipótese estatística padrão é que zero pessoas se machucaram naquela categoria específica.
    - Permite converter a coluna de Float (número quebrado) para Int (número inteiro), já que não existem "1.5 pessoas mortas".

In [34]:
colunas_texto = [
    'Numero_da_Ficha', 'Operador_Padronizado', 'Classificacao_da_Ocorrencia','Data_da_Ocorrencia', 'Hora_da_Ocorrencia',
    'Municipio', 'UF', 'Regiao', 'Descricao_do_Tipo', 'ICAO', 'Latitude', 'Longitude', 'Tipo_de_Aerodromo', 'Historico',
    'Matricula', 'Categoria_da_Aeronave', 'Operador', 'Tipo_de_Ocorrencia', 'Fase_da_Operacao', 'Operacao', 'Danos_a_Aeronave',
    'Aerodromo_de_Destino', 'Aerodromo_de_Origem', 'Modelo', 'CLS', 'Tipo_ICAO', 'PMD', 'Numero_de_Assentos', 'Nome_do_Fabricante',
    'PSSO'
]

print("=== 1. QUANTIDADE DE NaNs ANTES DA LIMPEZA ===")
print(df[colunas_texto].isna().sum())
print("-" * 50)

def preencher_nan_texto(dataframe: pd.DataFrame, lista_colunas: list) -> pd.DataFrame:
    """
    Substitui os valores NaN das colunas de texto pelo texto "Desconhecido".
    """
    df_copia2 = dataframe.copy()
    df_copia2[lista_colunas] = df_copia2[lista_colunas].fillna('Desconhecido')
    return df_copia2

df_tratado = preencher_nan_texto(df, colunas_texto)

print("=== 2. QUANTIDADE DE NaNs DEPOIS DA LIMPEZA ===")
print(df_tratado[colunas_texto].isna().sum())
print("-" * 50)

=== 1. QUANTIDADE DE NaNs ANTES DA LIMPEZA ===
Numero_da_Ficha                   2
Operador_Padronizado             76
Classificacao_da_Ocorrencia       0
Data_da_Ocorrencia                0
Hora_da_Ocorrencia             1433
Municipio                      1394
UF                                3
Regiao                          670
Descricao_do_Tipo               642
ICAO                           3334
Latitude                       1490
Longitude                      1490
Tipo_de_Aerodromo              3449
Historico                       265
Matricula                         4
Categoria_da_Aeronave             9
Operador                         76
Tipo_de_Ocorrencia              642
Fase_da_Operacao               1300
Operacao                         94
Danos_a_Aeronave               1426
Aerodromo_de_Destino           2138
Aerodromo_de_Origem            2117
Modelo                          163
CLS                             175
Tipo_ICAO                       158
PMD                             145
Numero_de_Assentos              149
Nome_do_Fabricante              291
PSSO                              0
dtype: int64
--------------------------------------------------
=== 2. QUANTIDADE DE NaNs DEPOIS DA LIMPEZA ===
Numero_da_Ficha                0
Operador_Padronizado           0
Classificacao_da_Ocorrencia    0
Data_da_Ocorrencia             0
Hora_da_Ocorrencia             0
Municipio                      0
UF                             0
Regiao                         0
Descricao_do_Tipo              0
ICAO                           0
Latitude                       0
Longitude                      0
Tipo_de_Aerodromo              0
Historico                      0
Matricula                      0
Categoria_da_Aeronave          0
Operador                       0
Tipo_de_Ocorrencia             0
Fase_da_Operacao               0
Operacao                       0
Danos_a_Aeronave               0
Aerodromo_de_Destino           0
Aerodromo_de_Origem            0
Modelo                         0
CLS                            0
Tipo_ICAO                      0
PMD                            0
Numero_de_Assentos             0
Nome_do_Fabricante             0
PSSO                           0
dtype: int64
--------------------------------------------------

In [31]:
# 1. Lista com as colunas de lesões e contagem da base
colunas_lesoes = [
    'Lesoes_Fatais_Tripulantes', 'Lesoes_Fatais_Passageiros', 'Lesoes_Fatais_Terceiros',
    'Lesoes_Graves_Tripulantes', 'Lesoes_Graves_Passageiros', 'Lesoes_Graves_Terceiros',
    'Lesoes_Leves_Tripulantes', 'Lesoes_Leves_Passageiros', 'Lesoes_Leves_Terceiros',
    'Ilesos_Tripulantes', 'Ilesos_Passageiros',
    'Lesoes_Desconhecidas_Tripulantes', 'Lesoes_Desconhecidas_Passageiros', 'Lesoes_Desconhecidas_Terceiros'
]

# --- ANTES ---
print("=== 1. QUANTIDADE DE NaNs ANTES DA LIMPEZA ===")
# Soma quantos NaNs existem apenas nas colunas da lista
print(df[colunas_lesoes].isna().sum())
print("-" * 50)


# 2. Criar a função de preenchimento
def preencher_nan_lesoes(dataframe: pd.DataFrame, lista_colunas: list) -> pd.DataFrame:
    """
    Substitui os valores NaN das colunas de lesões pelo número zero (0).
    Aplica a conversão para tipo inteiro (Int64), ideal para contagens.
    """
    # Faz uma cópia para não alterar o DataFrame original por acidente
    df_copia = dataframe.copy()

    # Preenche os NaNs com 0 e converte para tipo numérico inteiro
    df_copia[lista_colunas] = df_copia[lista_colunas].fillna(0).astype('int64')

    return df_copia


# 3. Aplicar a função no seu DataFrame
df_tratado = preencher_nan_lesoes(df, colunas_lesoes)


# --- DEPOIS ---
print("=== 2. QUANTIDADE DE NaNs DEPOIS DA LIMPEZA ===")
print(df_tratado[colunas_lesoes].isna().sum())
print("-" * 50)

=== 1. QUANTIDADE DE NaNs ANTES DA LIMPEZA ===
Lesoes_Fatais_Tripulantes           1118
Lesoes_Fatais_Passageiros           1239
Lesoes_Fatais_Terceiros             1319
Lesoes_Graves_Tripulantes           1168
Lesoes_Graves_Passageiros           1281
Lesoes_Graves_Terceiros             1327
Lesoes_Leves_Tripulantes            1124
Lesoes_Leves_Passageiros            1277
Lesoes_Leves_Terceiros              1327
Ilesos_Tripulantes                   410
Ilesos_Passageiros                   949
Lesoes_Desconhecidas_Tripulantes    1315
Lesoes_Desconhecidas_Passageiros    1326
Lesoes_Desconhecidas_Terceiros      1327
dtype: int64
--------------------------------------------------
=== 2. QUANTIDADE DE NaNs DEPOIS DA LIMPEZA ===
Lesoes_Fatais_Tripulantes           0
Lesoes_Fatais_Passageiros           0
Lesoes_Fatais_Terceiros             0
Lesoes_Graves_Tripulantes           0
Lesoes_Graves_Passageiros           0
Lesoes_Graves_Terceiros             0
Lesoes_Leves_Tripulantes            0
Lesoes_Leves_Passageiros            0
Lesoes_Leves_Terceiros              0
Ilesos_Tripulantes                  0
Ilesos_Passageiros                  0
Lesoes_Desconhecidas_Tripulantes    0
Lesoes_Desconhecidas_Passageiros    0
Lesoes_Desconhecidas_Terceiros      0
dtype: int64
--------------------------------------------------

##Traduzindo as ocorrências de vôo

Todas as ocorrências foram traduzidas para melhor entendimento do evento

In [33]:
print("=== 1. ANTES DA TRADUÇÃO DAS OCORRÊNCIAS ===")
print(df["Tipo_de_Ocorrencia"].unique())
print("-" * 50)

# 1. Criar o dicionário com a tradução dos principais códigos do CENIPA/CICTT
dicionario = {
    'RE': 'Excursão de pista',
    'OTHR': 'Outros motivos',
    'CTOL': 'Colisão com obstáculo decolagem/pouso',
    'SCF-NP': 'Falha de componente (exceto motor)',
    'SCF-PP': 'Falha do motor/propulsão',
    'ARC': 'Contato anormal com a pista',
    'LALT': 'Operação em baixa altitude',
    'LOC-G': 'Perda de controle no solo',
    'LOC-I': 'Perda de controle em voo',
    'RAMP': 'Problemas em rampa/pátio',
    'ADRM': 'Problemas no aeródromo/infraestrutura',
    'UNK': 'Desconhecido',
    'WSTRW': 'Vento severo (Windshear)',
    'SEC': 'Atos ilícitos/sabotagem',
    'RI': 'Incursão em pista',
    'FUEL': 'Problemas de combustível',
    'ATM/CNS': 'Falha no tráfego aéreo/comunicação',
    'UIMC': 'Neblina/nuvens',
    'BIRD': 'Colisão com pássaro',
    'CFIT': 'Colisão sem perda de controle',
    'MAC': 'Colisão entre aeronaves em voo',
    'GTOW': 'Reboque',
    'AMAN': 'Manobra abrupta',
    'USOS': 'Pouso antes/depois da pista',
    'GCOL': 'Colisão entre aeronaves/veículos no solo',
    'EXTL': 'Problemas com carga externa (helicóptero)',
    'LOLI': 'Perda de sustentação em voo (Estol)',
    'F-NI': 'Fogo/fumaça a bordo',
    'MED': 'Emergência médica a bordo',
    'WILD': 'Animal selvagem na pista (exceto pássaros)',
    'EVAC': 'Evacuação de emergência da aeronave',
    'TURB': 'Turbulência severa',
    'F-POST': 'Fogo após o impacto/colisão',
    'ICE': 'Formação de gelo'
}

# 2. Aplicar o mapeamento criando uma coluna nova de fácil leitura
df["Tipo_Ocorrencia_Legivel"] = df["Tipo_de_Ocorrencia"].map(dicionario)

# 3. Mostrar os novos resultados únicos sem códigos complicados

print(df["Tipo_Ocorrencia_Legivel"].unique())

['RE' 'OTHR' 'CTOL' 'SCF-NP' 'SCF-PP' 'ARC' 'LALT' 'LOC-G' 'LOC-I' 'RAMP'
 'ADRM' 'UNK' 'WSTRW' 'SEC' 'RI' 'FUEL' 'ATM/CNS' 'UIMC' 'BIRD' 'CFIT'
 'MAC' nan 'GTOW' 'AMAN' 'USOS' 'GCOL' 'EXTL' 'LOLI' 'F-NI' 'MED' 'WILD'
 'EVAC' 'TURB' 'F-POST' 'ICE']
['Excursão de pista' 'Outros motivos'
 'Colisão com obstáculo decolagem/pouso'
 'Falha de componente (exceto motor)' 'Falha do motor/propulsão'
 'Contato anormal com a pista' 'Operação em baixa altitude'
 'Perda de controle no solo' 'Perda de controle em voo'
 'Problemas em rampa/pátio' 'Problemas no aeródromo/infraestrutura'
 'Desconhecido' 'Vento severo (Windshear)' 'Atos ilícitos/sabotagem'
 'Incursão em pista' 'Problemas de combustível'
 'Falha no tráfego aéreo/comunicação' 'Neblina/nuvens'
 'Colisão com pássaro' 'Colisão sem perda de controle'
 'Colisão entre aeronaves em voo' nan 'Reboque' 'Manobra abrupta'
 'Pouso antes/depois da pista' 'Colisão entre aeronaves/veículos no solo'
 'Problemas com carga externa (helicóptero)'
 'Perda de sustentação em voo (Estol)' 'Fogo/fumaça a bordo'
 'Emergência médica a bordo' 'Animal selvagem na pista (exceto pássaros)'
 'Evacuação de emergência da aeronave' 'Turbulência severa'
 'Fogo após o impacto/colisão' 'Formação de gelo']

In [35]:
print("=== 1. ANTES DA TRADUÇÃO DAS OCORRÊNCIAS ===")
print(df["Tipo_de_Ocorrencia"].unique())
print("-" * 50)

# 1. Criar o dicionário com a tradução dos principais códigos do CENIPA/CICTT
dicionario = {
    'RE': 'Excursão de pista',
    'OTHR': 'Outros motivos',
    'CTOL': 'Colisão com obstáculo decolagem/pouso',
    'SCF-NP': 'Falha de componente (exceto motor)',
    'SCF-PP': 'Falha do motor/propulsão',
    'ARC': 'Contato anormal com a pista',
    'LALT': 'Operação em baixa altitude',
    'LOC-G': 'Perda de controle no solo',
    'LOC-I': 'Perda de controle em voo',
    'RAMP': 'Problemas em rampa/pátio',
    'ADRM': 'Problemas no aeródromo/infraestrutura',
    'UNK': 'Desconhecido',
    'WSTRW': 'Vento severo (Windshear)',
    'SEC': 'Atos ilícitos/sabotagem',
    'RI': 'Incursão em pista',
    'FUEL': 'Problemas de combustível',
    'ATM/CNS': 'Falha no tráfego aéreo/comunicação',
    'UIMC': 'Neblina/nuvens',
    'BIRD': 'Colisão com pássaro',
    'CFIT': 'Colisão sem perda de controle',
    'MAC': 'Colisão entre aeronaves em voo',
    'GTOW': 'Reboque',
    'AMAN': 'Manobra abrupta',
    'USOS': 'Pouso antes/depois da pista',
    'GCOL': 'Colisão entre aeronaves/veículos no solo',
    'EXTL': 'Problemas com carga externa (helicóptero)',
    'LOLI': 'Perda de sustentação em voo (Estol)',
    'F-NI': 'Fogo/fumaça a bordo',
    'MED': 'Emergência médica a bordo',
    'WILD': 'Animal selvagem na pista (exceto pássaros)',
    'EVAC': 'Evacuação de emergência da aeronave',
    'TURB': 'Turbulência severa',
    'F-POST': 'Fogo após o impacto/colisão',
    'ICE': 'Formação de gelo'
}

# 2. Aplicar o mapeamento criando uma coluna nova de fácil leitura
df_tratado["Tipo_Ocorrencia_Legivel"] = df_tratado["Tipo_de_Ocorrencia"].map(dicionario)

# 3. Mostrar os novos resultados únicos sem códigos complicados
print("=== 2. DEPOIS DA TRADUÇÃO DAS OCORRÊNCIAS ===")
print(df_tratado["Tipo_Ocorrencia_Legivel"].unique())
print("-" * 50)

df_tratado.head()

=== 1. ANTES DA TRADUÇÃO DAS OCORRÊNCIAS ===
['RE' 'OTHR' 'CTOL' 'SCF-NP' 'SCF-PP' 'ARC' 'LALT' 'LOC-G' 'LOC-I' 'RAMP'
 'ADRM' 'UNK' 'WSTRW' 'SEC' 'RI' 'FUEL' 'ATM/CNS' 'UIMC' 'BIRD' 'CFIT'
 'MAC' nan 'GTOW' 'AMAN' 'USOS' 'GCOL' 'EXTL' 'LOLI' 'F-NI' 'MED' 'WILD'
 'EVAC' 'TURB' 'F-POST' 'ICE']
--------------------------------------------------
=== 2. DEPOIS DA TRADUÇÃO DAS OCORRÊNCIAS ===
['Excursão de pista' 'Outros motivos'
 'Colisão com obstáculo decolagem/pouso'
 'Falha de componente (exceto motor)' 'Falha do motor/propulsão'
 'Contato anormal com a pista' 'Operação em baixa altitude'
 'Perda de controle no solo' 'Perda de controle em voo'
 'Problemas em rampa/pátio' 'Problemas no aeródromo/infraestrutura'
 'Desconhecido' 'Vento severo (Windshear)' 'Atos ilícitos/sabotagem'
 'Incursão em pista' 'Problemas de combustível'
 'Falha no tráfego aéreo/comunicação' 'Neblina/nuvens'
 'Colisão com pássaro' 'Colisão sem perda de controle'
 'Colisão entre aeronaves em voo' nan 'Reboque' 'Manobra abrupta'
 'Pouso antes/depois da pista' 'Colisão entre aeronaves/veículos no solo'
 'Problemas com carga externa (helicóptero)'
 'Perda de sustentação em voo (Estol)' 'Fogo/fumaça a bordo'
 'Emergência médica a bordo' 'Animal selvagem na pista (exceto pássaros)'
 'Evacuação de emergência da aeronave' 'Turbulência severa'
 'Fogo após o impacto/colisão' 'Formação de gelo']
--------------------------------------------------

,Numero_da_Ocorrencia,Numero_da_Ficha,Operador_Padronizado,Classificacao_da_Ocorrencia,Data_da_Ocorrencia,Hora_da_Ocorrencia,Municipio,UF,Regiao,Descricao_do_Tipo,...,Lesoes_Desconhecidas_Passageiros,Lesoes_Desconhecidas_Terceiros,Modelo,CLS,Tipo_ICAO,PMD,Numero_de_Assentos,Nome_do_Fabricante,PSSO,Tipo_Ocorrencia_Legivel
0,36746,2023765949,NITZ AVIACAO AGRICOLA LTDA. - EPP,Acidente,2023-03-23,11:20:00,PASSO DO SOBRADO,RS,Sul,EXCURSÃO DE PISTA,...,NaN,NaN,A188B,L1P,C188,1497.0,1.0,CESSNA AIRCRAFT,verdadeiro,Excursão de pista
1,38381,202385892466,ENOCK RESENDE JUNIOR,Acidente,2023-07-09,16:00:00,SANTANA DO RIACHO,MG,Sudeste,OUTROS,...,NaN,NaN,H2,G1P,ZZZZ,500.0,2.0,ENOCK RESENDE JUNIOR,verdadeiro,Outros motivos
2,36409,2023525502,MS ARMAZENS GERAIS LTDA.,Incidente Grave,2023-02-16,19:00:00,TAILÂNDIA,PA,Norte,COLISÃO COM OBSTÁCULO DURANTE A DECOLAGEM E POUSO,...,NaN,NaN,SR22,L1P,SR22,1542.0,4.0,CIRRUS DESIGN,verdadeiro,Colisão com obstáculo decolagem/pouso
3,31607,2022464840,ADRIANO AUGUSTO PECLAT DE PAULA,Incidente Grave,2022-03-27,13:50,PIRENÓPOLIS,GO,Centro-Oeste,EXCURSÃO DE PISTA,...,NaN,NaN,PA-28R-201T,L1P,P28R,1315.0,4.0,PIPER AIRCRAFT,verdadeiro,Excursão de pista
4,31607,2022464840,ANTONIO PAULO MACHADO GONTIJO,Incidente Grave,2022-03-27,13:50,PIRENÓPOLIS,GO,Centro-Oeste,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,...,NaN,NaN,PA-28R-201T,L1P,P28R,1315.0,4.0,PIPER AIRCRAFT,verdadeiro,Falha de componente (exceto motor)

In [24]:
print(df["CLS"].unique())

['L1P' 'G1P' 'L2J' 'L2P' 'H1T' 'L1T' nan 'L2T' 'H1P' 'H2T' 'L00' 'A1P'
 'L1J' 'A1T' 'L3J' 'S1P' 'L4J']